// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sqlc

import (
	"context"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (
  id, role, content, tool_calls, tool_call_id, transport, external_id, context_ref, created_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, role, content, tool_calls, tool_call_id, transport, external_id, context_ref, created_at
`

type CreateConversationParams struct {
	ID         string
	Role       string
	Content    string
	ToolCalls  *string
	ToolCallID *string
	Transport  *string
	ExternalID *string
	ContextRef *string
	CreatedAt  string
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation,
		arg.ID,
		arg.Role,
		arg.Content,
		arg.ToolCalls,
		arg.ToolCallID,
		arg.Transport,
		arg.ExternalID,
		arg.ContextRef,
		arg.CreatedAt,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Content,
		&i.ToolCalls,
		&i.ToolCallID,
		&i.Transport,
		&i.ExternalID,
		&i.ContextRef,
		&i.CreatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, role, content, tool_calls, tool_call_id, transport, external_id, context_ref, created_at FROM conversations
WHERE id = ?
`

func (q *Queries) GetConversation(ctx context.Context, id string) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Content,
		&i.ToolCalls,
		&i.ToolCallID,
		&i.Transport,
		&i.ExternalID,
		&i.ContextRef,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationByTransportExternalID = `-- name: GetConversationByTransportExternalID :one
SELECT id, role, content, tool_calls, tool_call_id, transport, external_id, context_ref, created_at FROM conversations
WHERE transport = ? AND external_id = ?
`

type GetConversationByTransportExternalIDParams struct {
	Transport  *string
	ExternalID *string
}

func (q *Queries) GetConversationByTransportExternalID(ctx context.Context, arg GetConversationByTransportExternalIDParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByTransportExternalID, arg.Transport, arg.ExternalID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Content,
		&i.ToolCalls,
		&i.ToolCallID,
		&i.Transport,
		&i.ExternalID,
		&i.ContextRef,
		&i.CreatedAt,
	)
	return i, err
}

const hasInboundSince = `-- name: HasInboundSince :one
SELECT EXISTS (
  SELECT 1 FROM conversations
  WHERE role = ? AND created_at >= ?
)
`

type HasInboundSinceParams struct {
	Role      string
	CreatedAt string
}

// HasInboundSince answers "did the person send anything after this instant" -
// the whole of the morning briefing's reply detection (O8). It is a role check
// and a timestamp compare, deliberately not a context_ref match: the briefing
// asks an open question ("anything else for today?"), so any engagement counts
// as an answer and the message is never parsed. Recognition is context
// injection, not a gate, exactly as reconciliation does it.
//
// created_at is a fixed-width domain.TimeLayout string, so the >= compares
// chronologically as text. No index is warranted - conversations is capped by
// retention and this runs once per briefing-loop tick while the marker is set.
func (q *Queries) HasInboundSince(ctx context.Context, arg HasInboundSinceParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasInboundSince, arg.Role, arg.CreatedAt)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const latestContextRef = `-- name: LatestContextRef :one
SELECT context_ref FROM conversations
WHERE context_ref LIKE ?
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// LatestContextRef is the most recent context_ref matching a prefix pattern -
// 'reconcile:%' for a check-in, and the same shape for the briefing P3.5 adds.
// It is what names the open question in the agent's Context ref block: the
// reply to a 21:00 check-in read at 00:15 is answering reconcile:{yesterday},
// and only the row itself knows that.
//
// This is the first reader context_ref has ever had. It was written from the
// session the reconciler started sending, and left unread until there was a
// reply path to read it for.
//
// Whether a check-in is still open is deliberately not decided here.
// ListAwaitingReconciliation answers that, from the occurrences themselves,
// and the caller renders nothing when that set is empty. Asking a conversations
// row whether its question still stands would be a second answer to a question
// the occurrence rows already answer, and the two would eventually disagree.
//
// No index on context_ref, and none is warranted: conversations is capped by
// 180-day retention and this runs once per turn, against a table the ladder
// already scans for its own history.
func (q *Queries) LatestContextRef(ctx context.Context, contextRef *string) (*string, error) {
	row := q.db.QueryRowContext(ctx, latestContextRef, contextRef)
	var context_ref *string
	err := row.Scan(&context_ref)
	return context_ref, err
}

const listRecentConversations = `-- name: ListRecentConversations :many
SELECT id, role, content, tool_calls, tool_call_id, transport, external_id, context_ref, created_at FROM conversations
ORDER BY created_at DESC, id DESC
LIMIT ?
`

func (q *Queries) ListRecentConversations(ctx context.Context, limit int64) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listRecentConversations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.ToolCallID,
			&i.Transport,
			&i.ExternalID,
			&i.ContextRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
