// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sqlc

import (
	"context"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (
  id, role, content, tool_calls, tool_call_id, transport, external_id, context_ref, created_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, role, content, tool_calls, tool_call_id, transport, external_id, context_ref, created_at
`

type CreateConversationParams struct {
	ID         string
	Role       string
	Content    string
	ToolCalls  *string
	ToolCallID *string
	Transport  *string
	ExternalID *string
	ContextRef *string
	CreatedAt  string
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation,
		arg.ID,
		arg.Role,
		arg.Content,
		arg.ToolCalls,
		arg.ToolCallID,
		arg.Transport,
		arg.ExternalID,
		arg.ContextRef,
		arg.CreatedAt,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Content,
		&i.ToolCalls,
		&i.ToolCallID,
		&i.Transport,
		&i.ExternalID,
		&i.ContextRef,
		&i.CreatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, role, content, tool_calls, tool_call_id, transport, external_id, context_ref, created_at FROM conversations
WHERE id = ?
`

func (q *Queries) GetConversation(ctx context.Context, id string) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Content,
		&i.ToolCalls,
		&i.ToolCallID,
		&i.Transport,
		&i.ExternalID,
		&i.ContextRef,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationByTransportExternalID = `-- name: GetConversationByTransportExternalID :one
SELECT id, role, content, tool_calls, tool_call_id, transport, external_id, context_ref, created_at FROM conversations
WHERE transport = ? AND external_id = ?
`

type GetConversationByTransportExternalIDParams struct {
	Transport  *string
	ExternalID *string
}

func (q *Queries) GetConversationByTransportExternalID(ctx context.Context, arg GetConversationByTransportExternalIDParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByTransportExternalID, arg.Transport, arg.ExternalID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Content,
		&i.ToolCalls,
		&i.ToolCallID,
		&i.Transport,
		&i.ExternalID,
		&i.ContextRef,
		&i.CreatedAt,
	)
	return i, err
}
