// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package sqlc

import (
	"context"
)

const createGoal = `-- name: CreateGoal :one

INSERT INTO goals (
  id, title, period_kind, period_start, period_end,
  item_id, target_count, status, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, title, period_kind, period_start, period_end,
    item_id, target_count, status, created_at, updated_at
`

type CreateGoalParams struct {
	ID          string
	Title       string
	PeriodKind  string
	PeriodStart string
	PeriodEnd   string
	ItemID      *string
	TargetCount *int64
	Status      string
	CreatedAt   string
	UpdatedAt   string
}

// Goals and goal_updates (P3.5, docs/11-goals-spec.md). This file is ASCII-only
// and every UPDATE spells its RETURNING column list out rather than using *,
// matching items.sql: sqlc's SQLite query rewriter has a byte-offset bug that a
// single non-ASCII character earlier in the file is enough to trigger.
//
// There is deliberately no query here for item-linked progress or velocity.
// Both are a count over the chains view, which sqlc's analyzer cannot parse and
// which sqlc.yaml therefore omits from the schema set. That count is
// hand-written database/sql in internal/store/goals.go, the same exception
// chains.go already is.
// CreateGoal writes a goal. Status is always 'active' at creation.
func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, createGoal,
		arg.ID,
		arg.Title,
		arg.PeriodKind,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.ItemID,
		arg.TargetCount,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.PeriodKind,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.ItemID,
		&i.TargetCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGoalUpdate = `-- name: CreateGoalUpdate :one
INSERT INTO goal_updates (
  id, goal_id, note, progress_pct, source, created_at
) VALUES (
  ?, ?, ?, ?, ?, ?
)
RETURNING id, goal_id, note, progress_pct, source, created_at
`

type CreateGoalUpdateParams struct {
	ID          string
	GoalID      string
	Note        *string
	ProgressPct *int64
	Source      string
	CreatedAt   string
}

func (q *Queries) CreateGoalUpdate(ctx context.Context, arg CreateGoalUpdateParams) (GoalUpdate, error) {
	row := q.db.QueryRowContext(ctx, createGoalUpdate,
		arg.ID,
		arg.GoalID,
		arg.Note,
		arg.ProgressPct,
		arg.Source,
		arg.CreatedAt,
	)
	var i GoalUpdate
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.Note,
		&i.ProgressPct,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const getGoal = `-- name: GetGoal :one
SELECT id, title, period_kind, period_start, period_end,
    item_id, target_count, status, created_at, updated_at
FROM goals
WHERE id = ?
`

func (q *Queries) GetGoal(ctx context.Context, id string) (Goal, error) {
	row := q.db.QueryRowContext(ctx, getGoal, id)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.PeriodKind,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.ItemID,
		&i.TargetCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestGoalUpdate = `-- name: LatestGoalUpdate :one
SELECT id, goal_id, note, progress_pct, source, created_at
FROM goal_updates
WHERE goal_id = ?
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// LatestGoalUpdate is a freestanding goal's current progress: a read of the
// newest row, never a stored column, so it cannot drift from the log that
// produced it. ErrNotFound means the goal has had no update at all, which the
// period-end pass reads as missed.
func (q *Queries) LatestGoalUpdate(ctx context.Context, goalID string) (GoalUpdate, error) {
	row := q.db.QueryRowContext(ctx, latestGoalUpdate, goalID)
	var i GoalUpdate
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.Note,
		&i.ProgressPct,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveGoals = `-- name: ListActiveGoals :many
SELECT id, title, period_kind, period_start, period_end,
    item_id, target_count, status, created_at, updated_at
FROM goals
WHERE status = 'active'
ORDER BY created_at, id
`

// ListActiveGoals is the set context injection and the briefing both read, so
// it is ordered deterministically rather than left to the planner.
func (q *Queries) ListActiveGoals(ctx context.Context) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listActiveGoals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PeriodKind,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.ItemID,
			&i.TargetCount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllGoals = `-- name: ListAllGoals :many
SELECT id, title, period_kind, period_start, period_end,
    item_id, target_count, status, created_at, updated_at
FROM goals
ORDER BY created_at, id
`

func (q *Queries) ListAllGoals(ctx context.Context) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listAllGoals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PeriodKind,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.ItemID,
			&i.TargetCount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsPastPeriod = `-- name: ListGoalsPastPeriod :many
SELECT id, title, period_kind, period_start, period_end,
    item_id, target_count, status, created_at, updated_at
FROM goals
WHERE status = 'active' AND period_end < ?
ORDER BY period_end, id
`

// ListGoalsPastPeriod backs the sweeper's period-end evaluation. period_end is
// an inclusive local ISO date, so a goal is due once the local date has moved
// past it. status = 'active' is the whole idempotency guard: a goal this pass
// evaluates is written terminal in the same pass and no longer matches, and the
// transition is one-way, so an hourly re-run is a no-op (same shape as K6 for
// missed on occurrences).
func (q *Queries) ListGoalsPastPeriod(ctx context.Context, periodEnd string) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listGoalsPastPeriod, periodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PeriodKind,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.ItemID,
			&i.TargetCount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGoalStatus = `-- name: SetGoalStatus :execrows
UPDATE goals
SET status = ?, updated_at = ?
WHERE id = ? AND status = 'active'
`

type SetGoalStatusParams struct {
	Status    string
	UpdatedAt string
	ID        string
}

// SetGoalStatus is the sweeper's guarded one-way write. The AND status =
// 'active' clause makes a redundant hourly pass a benign zero-row update and
// absorbs a race with a concurrent abandoned from update_goal.
func (q *Queries) SetGoalStatus(ctx context.Context, arg SetGoalStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setGoalStatus, arg.Status, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET title = ?, period_start = ?, period_end = ?, target_count = ?,
    status = ?, updated_at = ?
WHERE id = ?
RETURNING id, title, period_kind, period_start, period_end,
    item_id, target_count, status, created_at, updated_at
`

type UpdateGoalParams struct {
	Title       string
	PeriodStart string
	PeriodEnd   string
	TargetCount *int64
	Status      string
	UpdatedAt   string
	ID          string
}

// UpdateGoal applies an update_goal edit. The terminal-goal guard is in Go
// (Layer 2), so this is only ever reached for an active goal; status is in the
// SET list for the one user-driven terminal transition, abandoned.
func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, updateGoal,
		arg.Title,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.TargetCount,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.PeriodKind,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.ItemID,
		&i.TargetCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
