// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlc

import (
	"context"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
  id, kind, title, notes, schedule, tz, tz_mode, notify_policy, priority,
  grace_period_minutes, reconcile_at, snooze_cap, attrs, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, kind, title, notes, schedule, tz, tz_mode, notify_policy, priority, grace_period_minutes, reconcile_at, snooze_cap, active, paused_until, archived_at, attrs, source, external_id, etag, last_synced_at, created_at, updated_at
`

type CreateItemParams struct {
	ID                 string
	Kind               string
	Title              string
	Notes              *string
	Schedule           string
	Tz                 string
	TzMode             string
	NotifyPolicy       string
	Priority           int64
	GracePeriodMinutes *int64
	ReconcileAt        *string
	SnoozeCap          int64
	Attrs              string
	CreatedAt          string
	UpdatedAt          string
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.ID,
		arg.Kind,
		arg.Title,
		arg.Notes,
		arg.Schedule,
		arg.Tz,
		arg.TzMode,
		arg.NotifyPolicy,
		arg.Priority,
		arg.GracePeriodMinutes,
		arg.ReconcileAt,
		arg.SnoozeCap,
		arg.Attrs,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Title,
		&i.Notes,
		&i.Schedule,
		&i.Tz,
		&i.TzMode,
		&i.NotifyPolicy,
		&i.Priority,
		&i.GracePeriodMinutes,
		&i.ReconcileAt,
		&i.SnoozeCap,
		&i.Active,
		&i.PausedUntil,
		&i.ArchivedAt,
		&i.Attrs,
		&i.Source,
		&i.ExternalID,
		&i.Etag,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, kind, title, notes, schedule, tz, tz_mode, notify_policy, priority, grace_period_minutes, reconcile_at, snooze_cap, active, paused_until, archived_at, attrs, source, external_id, etag, last_synced_at, created_at, updated_at FROM items
WHERE id = ?
`

func (q *Queries) GetItem(ctx context.Context, id string) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Title,
		&i.Notes,
		&i.Schedule,
		&i.Tz,
		&i.TzMode,
		&i.NotifyPolicy,
		&i.Priority,
		&i.GracePeriodMinutes,
		&i.ReconcileAt,
		&i.SnoozeCap,
		&i.Active,
		&i.PausedUntil,
		&i.ArchivedAt,
		&i.Attrs,
		&i.Source,
		&i.ExternalID,
		&i.Etag,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveItems = `-- name: ListActiveItems :many
SELECT id, kind, title, notes, schedule, tz, tz_mode, notify_policy, priority, grace_period_minutes, reconcile_at, snooze_cap, active, paused_until, archived_at, attrs, source, external_id, etag, last_synced_at, created_at, updated_at FROM items
WHERE active = 1 AND archived_at IS NULL
ORDER BY created_at, id
`

// ListActiveItems is the set injected into every agent turn, so it is ordered
// deterministically rather than left to the planner.
func (q *Queries) ListActiveItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listActiveItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Title,
			&i.Notes,
			&i.Schedule,
			&i.Tz,
			&i.TzMode,
			&i.NotifyPolicy,
			&i.Priority,
			&i.GracePeriodMinutes,
			&i.ReconcileAt,
			&i.SnoozeCap,
			&i.Active,
			&i.PausedUntil,
			&i.ArchivedAt,
			&i.Attrs,
			&i.Source,
			&i.ExternalID,
			&i.Etag,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
