// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llm_calls.sql

package sqlc

import (
	"context"
)

const createLLMCall = `-- name: CreateLLMCall :one
INSERT INTO llm_calls (
  id, task, tier, model, prompt_tokens, completion_tokens, latency_ms,
  escalated, escalation_reason, error, occurrence_id, created_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, task, tier, model, prompt_tokens, completion_tokens, latency_ms, escalated, escalation_reason, error, occurrence_id, created_at
`

type CreateLLMCallParams struct {
	ID               string
	Task             string
	Tier             int64
	Model            string
	PromptTokens     *int64
	CompletionTokens *int64
	LatencyMs        *int64
	Escalated        int64
	EscalationReason *string
	Error            *string
	OccurrenceID     *string
	CreatedAt        string
}

func (q *Queries) CreateLLMCall(ctx context.Context, arg CreateLLMCallParams) (LlmCall, error) {
	row := q.db.QueryRowContext(ctx, createLLMCall,
		arg.ID,
		arg.Task,
		arg.Tier,
		arg.Model,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.LatencyMs,
		arg.Escalated,
		arg.EscalationReason,
		arg.Error,
		arg.OccurrenceID,
		arg.CreatedAt,
	)
	var i LlmCall
	err := row.Scan(
		&i.ID,
		&i.Task,
		&i.Tier,
		&i.Model,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.LatencyMs,
		&i.Escalated,
		&i.EscalationReason,
		&i.Error,
		&i.OccurrenceID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLLMCallsOlderThan = `-- name: DeleteLLMCallsOlderThan :execrows
DELETE FROM llm_calls
WHERE created_at < ?
`

func (q *Queries) DeleteLLMCallsOlderThan(ctx context.Context, createdAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLLMCallsOlderThan, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listLLMCalls = `-- name: ListLLMCalls :many
SELECT id, task, tier, model, prompt_tokens, completion_tokens, latency_ms, escalated, escalation_reason, error, occurrence_id, created_at FROM llm_calls
ORDER BY created_at DESC, id DESC
LIMIT ?
`

func (q *Queries) ListLLMCalls(ctx context.Context, limit int64) ([]LlmCall, error) {
	rows, err := q.db.QueryContext(ctx, listLLMCalls, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmCall{}
	for rows.Next() {
		var i LlmCall
		if err := rows.Scan(
			&i.ID,
			&i.Task,
			&i.Tier,
			&i.Model,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.LatencyMs,
			&i.Escalated,
			&i.EscalationReason,
			&i.Error,
			&i.OccurrenceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
