// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Conversation struct {
	ID         string
	Role       string
	Content    string
	ToolCalls  *string
	ToolCallID *string
	Transport  *string
	ExternalID *string
	ContextRef *string
	CreatedAt  string
}

type Item struct {
	ID                 string
	Kind               string
	Title              string
	Notes              *string
	Schedule           string
	Tz                 string
	TzMode             string
	NotifyPolicy       string
	Priority           int64
	GracePeriodMinutes *int64
	ReconcileAt        *string
	SnoozeCap          int64
	Active             int64
	PausedUntil        *string
	ArchivedAt         *string
	Attrs              string
	Source             string
	ExternalID         *string
	Etag               *string
	LastSyncedAt       *string
	CreatedAt          string
	UpdatedAt          string
}

type Kv struct {
	Key       string
	Value     string
	UpdatedAt string
}

type LlmCall struct {
	ID               string
	Task             string
	Tier             int64
	Model            string
	PromptTokens     *int64
	CompletionTokens *int64
	LatencyMs        *int64
	Escalated        int64
	EscalationReason *string
	Error            *string
	OccurrenceID     *string
	CreatedAt        string
}

type Occurrence struct {
	ID                 string
	ItemID             string
	StartsAt           string
	EndsAt             *string
	Status             string
	IsOverride         int64
	ParentOccurrenceID *string
	SnoozeDepth        int64
	NotifiedAt         *string
	ReconciledAt       *string
	ResolvedAt         *string
	ResolutionNote     *string
	ResolutionSource   *string
	MessageText        *string
	MessageModel       *string
	MessageGeneratedAt *string
	GenerationAttempts int64
	GenerationPass     int64
	CreatedAt          string
}
