// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: occurrences.sql

package sqlc

import (
	"context"
)

const childOccurrence = `-- name: ChildOccurrence :one
SELECT id, item_id, starts_at, ends_at, status, is_override, parent_occurrence_id,
    snooze_depth, notified_at, reconciled_at, resolved_at, resolution_note,
    resolution_source, message_text, message_model, message_generated_at,
    generation_attempts, generation_pass, created_at
FROM occurrences
WHERE parent_occurrence_id = ?
`

// ChildOccurrence is the row a snooze wrote for its parent - the live link of
// a chain, one step down.
//
// It is :one because a snoozed row has exactly one child by construction: the
// second snooze of the same row is "already in the requested terminal state",
// which domain.Transition answers OutcomeNoop and which writes nothing. So a
// double-tapped Snooze button reads the child that already exists rather than
// minting a second one. idx_occ_parent covers the lookup.
//
// The column list is spelled out rather than *, and this comment is plain
// ASCII, matching OverrideFuturePendingOccurrence above - see items.sql's
// UpdateItem for the sqlc truncation bug both avoid.
func (q *Queries) ChildOccurrence(ctx context.Context, parentOccurrenceID *string) (Occurrence, error) {
	row := q.db.QueryRowContext(ctx, childOccurrence, parentOccurrenceID)
	var i Occurrence
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.IsOverride,
		&i.ParentOccurrenceID,
		&i.SnoozeDepth,
		&i.NotifiedAt,
		&i.ReconciledAt,
		&i.ResolvedAt,
		&i.ResolutionNote,
		&i.ResolutionSource,
		&i.MessageText,
		&i.MessageModel,
		&i.MessageGeneratedAt,
		&i.GenerationAttempts,
		&i.GenerationPass,
		&i.CreatedAt,
	)
	return i, err
}

const claimOccurrence = `-- name: ClaimOccurrence :execrows
UPDATE occurrences
SET status = 'notified', notified_at = ?
WHERE id = ?
  AND status = 'pending'
`

type ClaimOccurrenceParams struct {
	NotifiedAt *string
	ID         string
}

func (q *Queries) ClaimOccurrence(ctx context.Context, arg ClaimOccurrenceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimOccurrence, arg.NotifiedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countPendingOverdue = `-- name: CountPendingOverdue :one
SELECT count(*) FROM occurrences o
JOIN items i ON i.id = o.item_id
WHERE o.status = 'pending'
  AND o.starts_at <= ?
  AND o.starts_at >= ?
  AND i.kind = 'reminder'
  AND i.notify_policy = 'at_time'
  AND i.active = 1
  AND i.archived_at IS NULL
  AND ifnull(i.paused_until, '0000-01-01T00:00:00Z') <= ?
`

type CountPendingOverdueParams struct {
	StartsAt    string
	StartsAt_2  string
	PausedUntil *string
}

func (q *Queries) CountPendingOverdue(ctx context.Context, arg CountPendingOverdueParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingOverdue, arg.StartsAt, arg.StartsAt_2, arg.PausedUntil)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOccurrence = `-- name: CreateOccurrence :one
INSERT INTO occurrences (
  id, item_id, starts_at, ends_at, status, is_override,
  parent_occurrence_id, snooze_depth, message_text, created_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, item_id, starts_at, ends_at, status, is_override, parent_occurrence_id, snooze_depth, notified_at, reconciled_at, resolved_at, resolution_note, resolution_source, message_text, message_model, message_generated_at, generation_attempts, generation_pass, created_at
`

type CreateOccurrenceParams struct {
	ID                 string
	ItemID             string
	StartsAt           string
	EndsAt             *string
	Status             string
	IsOverride         int64
	ParentOccurrenceID *string
	SnoozeDepth        int64
	MessageText        *string
	CreatedAt          string
}

func (q *Queries) CreateOccurrence(ctx context.Context, arg CreateOccurrenceParams) (Occurrence, error) {
	row := q.db.QueryRowContext(ctx, createOccurrence,
		arg.ID,
		arg.ItemID,
		arg.StartsAt,
		arg.EndsAt,
		arg.Status,
		arg.IsOverride,
		arg.ParentOccurrenceID,
		arg.SnoozeDepth,
		arg.MessageText,
		arg.CreatedAt,
	)
	var i Occurrence
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.IsOverride,
		&i.ParentOccurrenceID,
		&i.SnoozeDepth,
		&i.NotifiedAt,
		&i.ReconciledAt,
		&i.ResolvedAt,
		&i.ResolutionNote,
		&i.ResolutionSource,
		&i.MessageText,
		&i.MessageModel,
		&i.MessageGeneratedAt,
		&i.GenerationAttempts,
		&i.GenerationPass,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFuturePendingOccurrence = `-- name: DeleteFuturePendingOccurrence :execrows
DELETE FROM occurrences
WHERE id = ?
  AND item_id = ?
  AND status = 'pending'
  AND is_override = 0
  AND starts_at > ?
`

type DeleteFuturePendingOccurrenceParams struct {
	ID       string
	ItemID   string
	StartsAt string
}

func (q *Queries) DeleteFuturePendingOccurrence(ctx context.Context, arg DeleteFuturePendingOccurrenceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFuturePendingOccurrence, arg.ID, arg.ItemID, arg.StartsAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getOccurrence = `-- name: GetOccurrence :one
SELECT id, item_id, starts_at, ends_at, status, is_override, parent_occurrence_id, snooze_depth, notified_at, reconciled_at, resolved_at, resolution_note, resolution_source, message_text, message_model, message_generated_at, generation_attempts, generation_pass, created_at FROM occurrences
WHERE id = ?
`

func (q *Queries) GetOccurrence(ctx context.Context, id string) (Occurrence, error) {
	row := q.db.QueryRowContext(ctx, getOccurrence, id)
	var i Occurrence
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.IsOverride,
		&i.ParentOccurrenceID,
		&i.SnoozeDepth,
		&i.NotifiedAt,
		&i.ReconciledAt,
		&i.ResolvedAt,
		&i.ResolutionNote,
		&i.ResolutionSource,
		&i.MessageText,
		&i.MessageModel,
		&i.MessageGeneratedAt,
		&i.GenerationAttempts,
		&i.GenerationPass,
		&i.CreatedAt,
	)
	return i, err
}

const listDueOccurrences = `-- name: ListDueOccurrences :many
SELECT o.id, o.item_id, o.starts_at, o.message_text,
       i.title, i.kind, i.priority
FROM occurrences o
JOIN items i ON i.id = o.item_id
WHERE o.status = 'pending'
  AND o.starts_at <= ?
  AND o.starts_at >= ?
  AND i.kind = 'reminder'
  AND i.notify_policy = 'at_time'
  AND i.active = 1
  AND i.archived_at IS NULL
  AND ifnull(i.paused_until, '0000-01-01T00:00:00Z') <= ?
ORDER BY o.starts_at, o.id
LIMIT ?
`

type ListDueOccurrencesParams struct {
	StartsAt    string
	StartsAt_2  string
	PausedUntil *string
	Limit       int64
}

type ListDueOccurrencesRow struct {
	ID          string
	ItemID      string
	StartsAt    string
	MessageText *string
	Title       string
	Kind        string
	Priority    int64
}

func (q *Queries) ListDueOccurrences(ctx context.Context, arg ListDueOccurrencesParams) ([]ListDueOccurrencesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDueOccurrences,
		arg.StartsAt,
		arg.StartsAt_2,
		arg.PausedUntil,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueOccurrencesRow{}
	for rows.Next() {
		var i ListDueOccurrencesRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.StartsAt,
			&i.MessageText,
			&i.Title,
			&i.Kind,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFutureOccurrencesForItem = `-- name: ListFutureOccurrencesForItem :many
SELECT id, item_id, starts_at, ends_at, status, is_override, parent_occurrence_id, snooze_depth, notified_at, reconciled_at, resolved_at, resolution_note, resolution_source, message_text, message_model, message_generated_at, generation_attempts, generation_pass, created_at FROM occurrences
WHERE item_id = ?
  AND starts_at > ?
ORDER BY starts_at, id
`

type ListFutureOccurrencesForItemParams struct {
	ItemID   string
	StartsAt string
}

func (q *Queries) ListFutureOccurrencesForItem(ctx context.Context, arg ListFutureOccurrencesForItemParams) ([]Occurrence, error) {
	rows, err := q.db.QueryContext(ctx, listFutureOccurrencesForItem, arg.ItemID, arg.StartsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Occurrence{}
	for rows.Next() {
		var i Occurrence
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.IsOverride,
			&i.ParentOccurrenceID,
			&i.SnoozeDepth,
			&i.NotifiedAt,
			&i.ReconciledAt,
			&i.ResolvedAt,
			&i.ResolutionNote,
			&i.ResolutionSource,
			&i.MessageText,
			&i.MessageModel,
			&i.MessageGeneratedAt,
			&i.GenerationAttempts,
			&i.GenerationPass,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOccurrencesForItem = `-- name: ListOccurrencesForItem :many
SELECT id, item_id, starts_at, ends_at, status, is_override, parent_occurrence_id, snooze_depth, notified_at, reconciled_at, resolved_at, resolution_note, resolution_source, message_text, message_model, message_generated_at, generation_attempts, generation_pass, created_at FROM occurrences
WHERE item_id = ?
ORDER BY starts_at, id
`

func (q *Queries) ListOccurrencesForItem(ctx context.Context, itemID string) ([]Occurrence, error) {
	rows, err := q.db.QueryContext(ctx, listOccurrencesForItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Occurrence{}
	for rows.Next() {
		var i Occurrence
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.IsOverride,
			&i.ParentOccurrenceID,
			&i.SnoozeDepth,
			&i.NotifiedAt,
			&i.ReconciledAt,
			&i.ResolvedAt,
			&i.ResolutionNote,
			&i.ResolutionSource,
			&i.MessageText,
			&i.MessageModel,
			&i.MessageGeneratedAt,
			&i.GenerationAttempts,
			&i.GenerationPass,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOccurrencesInRange = `-- name: ListOccurrencesInRange :many
SELECT o.id, o.item_id, o.starts_at, o.status, o.resolved_at, o.resolution_source,
       i.title
FROM occurrences o
JOIN items i ON i.id = o.item_id
WHERE o.starts_at >= ?
  AND o.starts_at < ?
  AND i.archived_at IS NULL
ORDER BY o.starts_at, o.id
`

type ListOccurrencesInRangeParams struct {
	StartsAt   string
	StartsAt_2 string
}

type ListOccurrencesInRangeRow struct {
	ID               string
	ItemID           string
	StartsAt         string
	Status           string
	ResolvedAt       *string
	ResolutionSource *string
	Title            string
}

// ListOccurrencesInRange is the agent's "today's occurrences" context block
// (docs/06-agent-spec.md#context-injection): every occurrence, across every
// item, starting inside [?, ?). Callers pass the device timezone's local-day
// bounds converted to instants, so "today" here always means the same day
// the rest of the injected context does. archived_at IS NULL excludes stale
// history left behind by a deleted item.
func (q *Queries) ListOccurrencesInRange(ctx context.Context, arg ListOccurrencesInRangeParams) ([]ListOccurrencesInRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, listOccurrencesInRange, arg.StartsAt, arg.StartsAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOccurrencesInRangeRow{}
	for rows.Next() {
		var i ListOccurrencesInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.StartsAt,
			&i.Status,
			&i.ResolvedAt,
			&i.ResolutionSource,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overrideFuturePendingOccurrence = `-- name: OverrideFuturePendingOccurrence :one
UPDATE occurrences
SET starts_at = ?, is_override = 1
WHERE id = ?
  AND item_id = ?
  AND status = 'pending'
  AND is_override = 0
  AND starts_at > ?
RETURNING id, item_id, starts_at, ends_at, status, is_override, parent_occurrence_id,
    snooze_depth, notified_at, reconciled_at, resolved_at, resolution_note,
    resolution_source, message_text, message_model, message_generated_at,
    generation_attempts, generation_pass, created_at
`

type OverrideFuturePendingOccurrenceParams struct {
	StartsAt   string
	ID         string
	ItemID     string
	StartsAt_2 string
}

// OverrideFuturePendingOccurrence is update_item's scope=single mechanism
// (05-schedule-spec.md#edit-scope): retime exactly one occurrence and mark it
// is_override, so the materializer's plan/delete cycle leaves it alone from
// then on. The guard mirrors DeleteFuturePendingOccurrence's exactly - only a
// pending, non-override, still-future row can be touched this way.
//
// RETURNING spells out its column list rather than using *, and this comment
// is plain ASCII, matching items.sql's UpdateItem/ArchiveItem - see the
// comment there for the sqlc bug this avoids.
func (q *Queries) OverrideFuturePendingOccurrence(ctx context.Context, arg OverrideFuturePendingOccurrenceParams) (Occurrence, error) {
	row := q.db.QueryRowContext(ctx, overrideFuturePendingOccurrence,
		arg.StartsAt,
		arg.ID,
		arg.ItemID,
		arg.StartsAt_2,
	)
	var i Occurrence
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.IsOverride,
		&i.ParentOccurrenceID,
		&i.SnoozeDepth,
		&i.NotifiedAt,
		&i.ReconciledAt,
		&i.ResolvedAt,
		&i.ResolutionNote,
		&i.ResolutionSource,
		&i.MessageText,
		&i.MessageModel,
		&i.MessageGeneratedAt,
		&i.GenerationAttempts,
		&i.GenerationPass,
		&i.CreatedAt,
	)
	return i, err
}

const releaseClaimedOccurrence = `-- name: ReleaseClaimedOccurrence :execrows
UPDATE occurrences
SET status = 'pending', notified_at = NULL
WHERE id = ?
  AND status = 'notified'
  AND notified_at = ?
`

type ReleaseClaimedOccurrenceParams struct {
	ID         string
	NotifiedAt *string
}

func (q *Queries) ReleaseClaimedOccurrence(ctx context.Context, arg ReleaseClaimedOccurrenceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseClaimedOccurrence, arg.ID, arg.NotifiedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resolveOccurrence = `-- name: ResolveOccurrence :execrows
UPDATE occurrences
SET status = ?, resolved_at = ?, resolution_note = ?, resolution_source = ?
WHERE id = ?
  AND status = ?
`

type ResolveOccurrenceParams struct {
	Status           string
	ResolvedAt       *string
	ResolutionNote   *string
	ResolutionSource *string
	ID               string
	Status_2         string
}

// ResolveOccurrence is POST /api/occurrences/{id}/resolve's write half, run
// only after domain.Transition has already answered OutcomeApplied. It writes
// all four resolution columns together because they are one fact - a row
// carrying a status but no resolved_at is not a resolution anyone can read.
//
// The trailing status = ? guard mirrors ClaimOccurrence's and
// ReleaseClaimedOccurrence's. The single BEGIN IMMEDIATE writer already makes
// the read above it and this write atomic, so the guard is redundant defence
// rather than the mechanism, and it is kept for the same reason every other
// guarded write in this file keeps one: a planner bug cannot reach a row the
// statement itself refuses.
func (q *Queries) ResolveOccurrence(ctx context.Context, arg ResolveOccurrenceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveOccurrence,
		arg.Status,
		arg.ResolvedAt,
		arg.ResolutionNote,
		arg.ResolutionSource,
		arg.ID,
		arg.Status_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
