// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: occurrences.sql

package sqlc

import (
	"context"
)

const claimOccurrence = `-- name: ClaimOccurrence :execrows
UPDATE occurrences
SET status = 'notified', notified_at = ?
WHERE id = ?
  AND status = 'pending'
`

type ClaimOccurrenceParams struct {
	NotifiedAt *string
	ID         string
}

func (q *Queries) ClaimOccurrence(ctx context.Context, arg ClaimOccurrenceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimOccurrence, arg.NotifiedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countPendingOverdue = `-- name: CountPendingOverdue :one
SELECT count(*) FROM occurrences o
JOIN items i ON i.id = o.item_id
WHERE o.status = 'pending'
  AND o.starts_at <= ?
  AND o.starts_at >= ?
  AND i.kind = 'reminder'
  AND i.notify_policy = 'at_time'
  AND i.active = 1
  AND i.archived_at IS NULL
  AND ifnull(i.paused_until, '0000-01-01T00:00:00Z') <= ?
`

type CountPendingOverdueParams struct {
	StartsAt    string
	StartsAt_2  string
	PausedUntil *string
}

func (q *Queries) CountPendingOverdue(ctx context.Context, arg CountPendingOverdueParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingOverdue, arg.StartsAt, arg.StartsAt_2, arg.PausedUntil)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOccurrence = `-- name: CreateOccurrence :one
INSERT INTO occurrences (
  id, item_id, starts_at, ends_at, status, is_override,
  parent_occurrence_id, snooze_depth, message_text, created_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, item_id, starts_at, ends_at, status, is_override, parent_occurrence_id, snooze_depth, notified_at, reconciled_at, resolved_at, resolution_note, resolution_source, message_text, message_model, message_generated_at, generation_attempts, generation_pass, created_at
`

type CreateOccurrenceParams struct {
	ID                 string
	ItemID             string
	StartsAt           string
	EndsAt             *string
	Status             string
	IsOverride         int64
	ParentOccurrenceID *string
	SnoozeDepth        int64
	MessageText        *string
	CreatedAt          string
}

func (q *Queries) CreateOccurrence(ctx context.Context, arg CreateOccurrenceParams) (Occurrence, error) {
	row := q.db.QueryRowContext(ctx, createOccurrence,
		arg.ID,
		arg.ItemID,
		arg.StartsAt,
		arg.EndsAt,
		arg.Status,
		arg.IsOverride,
		arg.ParentOccurrenceID,
		arg.SnoozeDepth,
		arg.MessageText,
		arg.CreatedAt,
	)
	var i Occurrence
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.IsOverride,
		&i.ParentOccurrenceID,
		&i.SnoozeDepth,
		&i.NotifiedAt,
		&i.ReconciledAt,
		&i.ResolvedAt,
		&i.ResolutionNote,
		&i.ResolutionSource,
		&i.MessageText,
		&i.MessageModel,
		&i.MessageGeneratedAt,
		&i.GenerationAttempts,
		&i.GenerationPass,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFuturePendingOccurrence = `-- name: DeleteFuturePendingOccurrence :execrows
DELETE FROM occurrences
WHERE id = ?
  AND item_id = ?
  AND status = 'pending'
  AND is_override = 0
  AND starts_at > ?
`

type DeleteFuturePendingOccurrenceParams struct {
	ID       string
	ItemID   string
	StartsAt string
}

func (q *Queries) DeleteFuturePendingOccurrence(ctx context.Context, arg DeleteFuturePendingOccurrenceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFuturePendingOccurrence, arg.ID, arg.ItemID, arg.StartsAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getOccurrence = `-- name: GetOccurrence :one
SELECT id, item_id, starts_at, ends_at, status, is_override, parent_occurrence_id, snooze_depth, notified_at, reconciled_at, resolved_at, resolution_note, resolution_source, message_text, message_model, message_generated_at, generation_attempts, generation_pass, created_at FROM occurrences
WHERE id = ?
`

func (q *Queries) GetOccurrence(ctx context.Context, id string) (Occurrence, error) {
	row := q.db.QueryRowContext(ctx, getOccurrence, id)
	var i Occurrence
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.IsOverride,
		&i.ParentOccurrenceID,
		&i.SnoozeDepth,
		&i.NotifiedAt,
		&i.ReconciledAt,
		&i.ResolvedAt,
		&i.ResolutionNote,
		&i.ResolutionSource,
		&i.MessageText,
		&i.MessageModel,
		&i.MessageGeneratedAt,
		&i.GenerationAttempts,
		&i.GenerationPass,
		&i.CreatedAt,
	)
	return i, err
}

const listDueOccurrences = `-- name: ListDueOccurrences :many
SELECT o.id, o.item_id, o.starts_at, o.message_text,
       i.title, i.kind, i.priority
FROM occurrences o
JOIN items i ON i.id = o.item_id
WHERE o.status = 'pending'
  AND o.starts_at <= ?
  AND o.starts_at >= ?
  AND i.kind = 'reminder'
  AND i.notify_policy = 'at_time'
  AND i.active = 1
  AND i.archived_at IS NULL
  AND ifnull(i.paused_until, '0000-01-01T00:00:00Z') <= ?
ORDER BY o.starts_at, o.id
LIMIT ?
`

type ListDueOccurrencesParams struct {
	StartsAt    string
	StartsAt_2  string
	PausedUntil *string
	Limit       int64
}

type ListDueOccurrencesRow struct {
	ID          string
	ItemID      string
	StartsAt    string
	MessageText *string
	Title       string
	Kind        string
	Priority    int64
}

func (q *Queries) ListDueOccurrences(ctx context.Context, arg ListDueOccurrencesParams) ([]ListDueOccurrencesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDueOccurrences,
		arg.StartsAt,
		arg.StartsAt_2,
		arg.PausedUntil,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueOccurrencesRow{}
	for rows.Next() {
		var i ListDueOccurrencesRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.StartsAt,
			&i.MessageText,
			&i.Title,
			&i.Kind,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFutureOccurrencesForItem = `-- name: ListFutureOccurrencesForItem :many
SELECT id, item_id, starts_at, ends_at, status, is_override, parent_occurrence_id, snooze_depth, notified_at, reconciled_at, resolved_at, resolution_note, resolution_source, message_text, message_model, message_generated_at, generation_attempts, generation_pass, created_at FROM occurrences
WHERE item_id = ?
  AND starts_at > ?
ORDER BY starts_at, id
`

type ListFutureOccurrencesForItemParams struct {
	ItemID   string
	StartsAt string
}

func (q *Queries) ListFutureOccurrencesForItem(ctx context.Context, arg ListFutureOccurrencesForItemParams) ([]Occurrence, error) {
	rows, err := q.db.QueryContext(ctx, listFutureOccurrencesForItem, arg.ItemID, arg.StartsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Occurrence{}
	for rows.Next() {
		var i Occurrence
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.IsOverride,
			&i.ParentOccurrenceID,
			&i.SnoozeDepth,
			&i.NotifiedAt,
			&i.ReconciledAt,
			&i.ResolvedAt,
			&i.ResolutionNote,
			&i.ResolutionSource,
			&i.MessageText,
			&i.MessageModel,
			&i.MessageGeneratedAt,
			&i.GenerationAttempts,
			&i.GenerationPass,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOccurrencesForItem = `-- name: ListOccurrencesForItem :many
SELECT id, item_id, starts_at, ends_at, status, is_override, parent_occurrence_id, snooze_depth, notified_at, reconciled_at, resolved_at, resolution_note, resolution_source, message_text, message_model, message_generated_at, generation_attempts, generation_pass, created_at FROM occurrences
WHERE item_id = ?
ORDER BY starts_at, id
`

func (q *Queries) ListOccurrencesForItem(ctx context.Context, itemID string) ([]Occurrence, error) {
	rows, err := q.db.QueryContext(ctx, listOccurrencesForItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Occurrence{}
	for rows.Next() {
		var i Occurrence
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.IsOverride,
			&i.ParentOccurrenceID,
			&i.SnoozeDepth,
			&i.NotifiedAt,
			&i.ReconciledAt,
			&i.ResolvedAt,
			&i.ResolutionNote,
			&i.ResolutionSource,
			&i.MessageText,
			&i.MessageModel,
			&i.MessageGeneratedAt,
			&i.GenerationAttempts,
			&i.GenerationPass,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseClaimedOccurrence = `-- name: ReleaseClaimedOccurrence :execrows
UPDATE occurrences
SET status = 'pending', notified_at = NULL
WHERE id = ?
  AND status = 'notified'
  AND notified_at = ?
`

type ReleaseClaimedOccurrenceParams struct {
	ID         string
	NotifiedAt *string
}

func (q *Queries) ReleaseClaimedOccurrence(ctx context.Context, arg ReleaseClaimedOccurrenceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseClaimedOccurrence, arg.ID, arg.NotifiedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
